# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-15 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_shows_app', '0002_auto_20191114_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shows',
            name='release_date',
        ),
        migrations.AddField(
            model_name='shows',
            name='released_at',
            field=models.DateField(null=True),
        ),
    ]
